from enum import Enum


class ResponseSignal(Enum):
    FILE_TYPE_NOT_SUPPORTED = "FILE_TYPE_NOT_SUPPORTED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_VALID = "FILE_VALIDATED_SUCCESS"
    FILE_UPLOADED = "FILE_UPLOADED_SUCCESS"
    PROCESSING_SUCCES="PROCESSING_SUCCES"
    PROCESSING_FAILED="PROCESSING_FAILED"

